<?php $projectConfig = Zend_Registry::get('projectConfig'); ?>

<?= $this->translate()->_('Hi') ?> <?= $this->username ?>,

<?= $this->translate()->_('we have received your password reset request. To reset your password, visit the link below within 24 hours.') ?>


<?= $this->translate()->_('Username') ?>:   <?= $this->username ?>

<?= $this->translate()->_('Email') ?>:     <?= $this->email ?>

<?= Zmz_Translate::_('Password reset link') ?>: <?= $projectConfig->siteUrl ?><?= $this->url(array('controller' => 'account', 'action' => 'confirmemail', 'id' => $this->user_id, 'code' => $this->code), 'default', true) ?>

<?= $this->partial('partials/_emailFooter.phtml') ?>
