<h3><?= $this->translate()->_('Account') ?></h3>
<ul>
    <li class="firstli"><a href="<?= $this->url(array('action' => 'index')) ?>"><?= $this->translate()->_('My account') ?></a></li>
    <li><a href="<?= $this->url(array('action' => 'edit')) ?>"><?= $this->translate()->_('Edit account') ?></a></li>

    <li><a href="<?= $this->url(array('action' => 'changepassword')) ?>"><?= $this->translate()->_('Change password') ?></a></li>
    <li><a href="<?= $this->url(array('action' => 'changeemail')) ?>"><?= $this->translate()->_('Change email') ?></a></li>

</ul>