<?php $projectConfig = Zend_Registry::get('projectConfig'); ?>

<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php
        $this->headTitle()->append($projectConfig->title);
        $this->headTitle()->setSeparator(' - ');
        $this->title ? $this->headTitle()->append($this->title) : null;
        ?>

        <?= $this->headTitle(); ?>       
        <?php
        $this->headLink()
//                ->appendStylesheet($this->baseUrl() . '/css/style.css', 'all')
                ->appendStylesheet($this->baseUrl() . '/css/form.css', 'all')
                ->appendStylesheet($this->baseUrl() . '/css/utils.css', 'all')
                ->appendStylesheet($this->baseUrl() . '/css/messenger.css', 'all')
                ->appendStylesheet($this->baseUrl() . '/css/bootstrap.min.css', 'all')
                ->appendStylesheet($this->baseUrl() . '/jquery/css/black-tie/jquery-ui-1.8.16.custom.css', 'all');

        $this->headScript()
                ->appendFile($this->baseUrl() . '/js/zmz')
                ->appendFile($this->baseUrl() . '/js/custom.js');

        $this->jQuery()
                ->setLocalPath($this->baseUrl() . '/jquery/js/jquery-1.6.2.min.js')
                ->setUiLocalPath($this->baseUrl() . '/jquery/js/jquery-ui-1.8.16.custom.min.js')
                ->uiEnable();
        ?>

        <?php $this->captureJavascript()->start() ?>
        <script type="text/javascript">
            $(".locale-link").click(function () {
                $("#dialog-locale").dialog({
                    height: 220,
                    width: 560,
                    modal: true
                });
                $("#dialog-locale-content").load('<?= $this->url(array('controller' => 'locale'), 'default', true) ?>', function () {
                    $(this).show();
                    $("#dialog-locale-loading").hide();
                });
                return false;
            });
        </script>
        <?php $this->addJquery($this->captureJavascript()->end()) ?>

        <?php $this->captureJavascript()->start() ?>
        <script type="text/javascript">
            function closeMessenger() {
                $("#messenger").fadeOut(300);
            }
        </script>
        <?php $this->addJavascript($this->captureJavascript()->end()) ?>
        <?= $this->jQuery() // must be called before headScript() ?>
        <?= $this->headScript() ?>
        <?= $this->headLink() ?>

    </head>
    <body>
        <div id="dialog-locale" title="<?= $this->translate()->_('Change your settings') ?>" class="hidden">
            <div id="dialog-locale-loading"><img src="/images/spinner.gif" alt="" /> <span><?= $this->translate()->_('Loading') ?>...</span></div>
            <div id="dialog-locale-content" class="hidden"></div>
        </div>

        <div class="topbar">
            <div class="fill">
                <div class="container">
                    <h3><a href="<?= $this->url(array(), 'default', true) ?>"><?= $projectConfig->title ?></a></h3>
                    <ul>
                        <li><a href="<?= $this->url(array(), 'default', true) ?>"><?= $this->translate()->_('Home') ?></a></li>
                        <li><a href="<?= $this->url(array('controller' => 'contact'), 'default', true) ?>"><?= $this->translate()->_('Contact') ?></a></li>
                    </ul>
                    <ul class="nav secondary-nav">

                        <?php if (Model_Acl::isLogged()): ?>
                            <li class="menu">
                                <a href="<?= $this->url(array("controller" => "account", "action" => "index"), 'default', true) ?>"><?= Model_Acl::getUsername() ?></a>
                            </li>
                            <li class="menu">
                                <a href="<?= $this->url(array("controller" => "account", "action" => "logout"), 'default', true) ?>"><?= $this->translate()->_('Logout') ?></a>
                            </li>
                        <?php else: ?>
                            <li class="menu">
                                <a href="<?= $this->url(array("controller" => "account", "action" => "login"), 'default', true) ?>"><?= $this->translate()->_('Login') ?></a>
                            </li>
                            <li class="menu">
                                <a href="<?= $this->url(array("controller" => "account", "action" => "signin"), 'default', true) ?>"><?= $this->translate()->_('Sign in') ?></a>
                            </li>

                        <?php endif; ?>
                    </ul>

                </div>
            </div>
        </div>

        <div class="container"> 

            <div style="height: 60px;"></div>
            <div id="messenger"><?= $this->messenger() ?></div>

            <?= $this->layout()->content ?>
            <footer>
                <div class="clear-float">
                    <div class="float-left">
                        <p>&copy; <?= $projectConfig->title ?> <?= date("Y") ?></p>
                    </div>
                    <div class="float-right">
                        <span><?= $this->translate()->_('Language') ?>:
                            <a class="locale-link" href="<?= $this->url(array(), 'default', true) ?>"><?= ucfirst(Zend_Locale::getTranslation(MyApp_Language::getLanguage(), 'language')); ?></a>
                        </span>
                        <span><?= $this->translate()->_('Timezone') ?>:
                            <a class="locale-link" href="<?= $this->url(array(), 'default', true) ?>"><?= Zmz_Culture::getTimezone(); ?></a>
                        </span>
                    </div>
                </div>
            </footer>
        </div>



    </body>
</html>
