<script type="text/javascript">
    var ZMZ = new Object();


    ZMZ.countAjaxFails = 0;

    ZMZ.getJSON = function(url, data, callback) {
        var value = jQuery.ajax({
            type: "GET",
            url: url,
            data: data,
            async: true,
            dataType: "json",
            success: function (data, textStatus, XMLHttpRequest) {
                ZMZ.countAjaxFails = 0;
                var json = null;
                var error = false;
                if (data.status == <?= Zmz_Json_Response::ERROR ?>) {
                    error = data.error;
                } else {
                    json = data.data;
                }
                callback.call(null, json, error);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                ZMZ.countAjaxFails++;
                alert('<?= $this->translate(1)->_("Network error, reload page if necessary") ?>');
                if (ZMZ.countAjaxFails > 8) {
                    location.reload();
                }
            }
        });
        return value;
    }

</script>